name: $name
version: $version
main: net.nightium.statusplugin.Status
description: $description
website: "https://github.com/ArisNight/StatusPaper"
authors:
  - ArisNight
  - Nightium
api-version: "$apiVersion"